### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/train_q&a.txt'

### ISSUE THREAD

**Issue by tengfeineu** [crownpku/Information-Extraction-Chinese#18]
FileNotFoundError: [Errno 2] No such file or directory: './data/train_q&a.txt'

我将项目clone下来发现没有/data目录

**Comment by tengfeineu** [comment]
搞定了，有其他问题在找您咨询

**Comment by GarrettZhen** [comment]
你好请问这个问题是怎么解决的

**Comment by GarrettZhen** [comment]
在运行  python3 initial.py 这个命令时，为什么会有No such file or directory: './data/train_q&a.txt'这个错误呢
