### ISSUE TITLE
封装实体识别的evaluate_line(),多个语句循环调用报错NotFoundError (see above for traceback): Key Variable_3 not found in checkpoint

### ISSUE THREAD

**Issue by AmberCa** [crownpku/Information-Extraction-Chinese#36]
我把实体识别的evaluate_line()封装成一个evaluate_line2(sentenceInfo)，在外层调用的代码是：
def test():
	sentenceInfos = ['李晓华和她的丈夫王大牛，还有同事李小明前日一起去英国旅行了', '王大牛命令李晓华在周末前完成这份代码。']
	for sentenceInfo in sentenceInfos:
		# print(sentenceInfo)
		print('---------------', sentenceInfo)
		entities = main.evaluate_line2(sentenceInfo)
		print('*'*10)
		print(entities)
在第二次循环时报错如下`NotFoundError (see above for traceback): Key Variable_3 not found in checkpoint`
	 [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_INT32, DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]
这是什么错误，我应该怎么修改啊，希望能解答，着急，谢谢了

**Comment by crownpku** [comment]
evaluate_line2的代码能给出吗？不清楚你里面是怎么改的

**Comment by AmberCa** [comment]
evaluate_line2(sentenceInfo)的方法是这样的：
def evaluate_line2(sentenceInfo):
    config = load_config(FLAGS.config_file)
    logger = get_logger(FLAGS.log_file)
    # limit GPU memory
    tf_config = tf.ConfigProto()
    tf_config.gpu_options.allow_growth = True
    with open(FLAGS.map_file, "rb") as f:
        char_to_id, id_to_char, tag_to_id, id_to_tag = pickle.load(f)
    with tf.Session(config=tf_config) as sess:
        model = create_model(sess, Model, FLAGS.ckpt_path, load_word2vec, config, id_to_char, logger)
        # while True:
            # try:
            #     line = input("请输入测试句子:")
            #     result = model.evaluate_line(sess, input_from_line(line, char_to_id), id_to_tag)
            #     print(result)
            # except Exception as e:
            #     logger.info(e)

        # line = input("请输入测试句子:")
        result = model.evaluate_line(sess, input_from_line(sentenceInfo, char_to_id), id_to_tag)
        print(result)
        return result

就是把原先的从控制台获取的句子，改成是入参的句子

**Comment by AmberCa** [comment]
def evaluate_line2(sentenceInfo):
config = load_config(FLAGS.config_file)
logger = get_logger(FLAGS.log_file)
# limit GPU memory
tf_config = tf.ConfigProto()
tf_config.gpu_options.allow_growth = True
with open(FLAGS.map_file, "rb") as f:
char_to_id, id_to_char, tag_to_id, id_to_tag = pickle.load(f)
with tf.Session(config=tf_config) as sess:
model = create_model(sess, Model, FLAGS.ckpt_path, load_word2vec, config, id_to_char, logger)
# while True:
# try:
# line = input("请输入测试句子:")
# result = model.evaluate_line(sess, input_from_line(line, char_to_id), id_to_tag)
# print(result)
# except Exception as e:
# logger.info(e)

- ****

**Comment by crownpku** [comment]
`for sentenceInfo in sentenceInfos`
把这个放去evaluate_line2里面去试试，参考我原来代码中while loop的写法。现在的写法相当于每次新来一个sentenceInfo都要把前面create_model跑一遍。

**Comment by AmberCa** [comment]
def evaluate_line2():#sentenceInfo
    config = load_config(FLAGS.config_file)
    logger = get_logger(FLAGS.log_file)
    # limit GPU memory
    tf_config = tf.ConfigProto()
    tf_config.gpu_options.allow_growth = True
    with open(FLAGS.map_file, "rb") as f:
        char_to_id, id_to_char, tag_to_id, id_to_tag = pickle.load(f)
    with tf.Session(config=tf_config) as sess:
        model = create_model(sess, Model, FLAGS.ckpt_path, load_word2vec, config, id_to_char, logger)
        # while True:
            # try:
            #     line = input("请输入测试句子:")
            #     result = model.evaluate_line(sess, input_from_line(line, char_to_id), id_to_tag)
            #     print(result)
            # except Exception as e:
            #     logger.info(e)

        # line = input("请输入测试句子:")
        **sentenceInfos = ['李晓华和她的丈夫王大牛，还有同事豆保军前日一起去英国旅行了', '王大牛命令李晓华在周末前完成这份代码。']
        for sentenceInfo in sentenceInfos:
            # print(sentenceInfo)
            print('---------------', sentenceInfo)
            result = model.evaluate_line(sess, input_from_line(sentenceInfo, char_to_id), id_to_tag)
            print(result)
            # return result**
这样写是可以的。
我的想法是把实体识别和关系提取组合起来，目前把这两个项目都组合起来了，想每次都把一个“句子”当做**参数**穿进去，先实体识别，然后关系提取，我应该怎么改程序，才能让实体识别作为一个有参数的方法，让外部调用呢，不知道您有没有方法或者思路实现这个功能我是新手，刚刚接触这方面，希望多指教，谢谢大佬了

**Comment by crownpku** [comment]
句子当参数传进去没有问题，只是initialization要先load NER和RE的模型进去，再循环对每个句子跑evaluate，不要每个句子都重新load一次model。

**Comment by AmberCa** [comment]
好的，我研究一下程序过程，谢谢大佬了
