### ISSUE TITLE
[RE_BGRU_2ATT]Data directory missing?

### ISSUE THREAD

**Issue by juncaofish** [crownpku/Information-Extraction-Chinese#5]
Just confirm if this folder is not provided.

**Comment by crownpku** [comment]
The original relationid, training and test data samples and word embedding are in RE_BGRU_2ATT/origin_data. You may provide your own training data according to the same format.

Then as mentioned in readme you have to run
```
#python3 initial.py
```
to generate .npy files that will be saved at /data folder.

**Comment by juncaofish** [comment]
Thanks! Will give it a try.

**Comment by crownpku** [comment]
If you need more data for training this task you may check out [a larger corpus here](https://github.com/crownpku/Small-Chinese-Corpus/tree/master/relation_multiple_chi).
