### ISSUE TITLE
[RE_BGRU_2ATT] 执行test_GRU.py报错

### ISSUE THREAD

**Issue by Whatdfdvdg** [crownpku/Information-Extraction-Chinese#7]
报错信息:
tensorflow.python.framework.errors_impl.NotFoundError: Key model/GRU_FORWARD/multi_rnn_cell/cell_0/gru_cell/gates/biases not found in checkpoint

怀疑是离线存储的模型的问题,我自己重新训练了一版,没有这个问题,只是数据有点少,效果不大好,楼主有更多的数据可以共享下吗

请输入中文句子，格式为 "name1 name2 sentence":李晓华 王大牛 李晓华和她的高中同学王大牛两个人前日一起去英国旅行
实体1: 李晓华
实体2: 王大牛
李晓华和她的高中同学王大牛两个人前日一起去英国旅行
关系是:
No.1: 夫妻, Probability is 0.345401
No.2: 父母, Probability is 0.178258
No.3: unknown, Probability is 0.135266
请输入中文句子，格式为 "name1 name2 sentence":李晓华 王大牛 王大牛命令李晓华在周末前完成这份代码。
实体1: 李晓华
实体2: 王大牛
王大牛命令李晓华在周末前完成这份代码。
关系是:
No.1: 父母, Probability is 0.257889
No.2: 夫妻, Probability is 0.207047
No.3: unknown, Probability is 0.0861223

**Comment by crownpku** [comment]
我把model中的checkpoint文件也上传了，你重新pull一下试试？

更多训练数据请参考https://github.com/crownpku/Small-Chinese-Corpus

**Comment by Whatdfdvdg** [comment]
ok thx
